with source as (

    select * from {{ source('censustract', 'svi_2022_us') }}

),

renamed as (

    select
        st,
        state,
        st_abbr,
        stcnty,
        county,
        fips as tractfips,
        location,
        cast (area_sqmi as float) as area_sqmi,
        cast (e_totpop as float) as e_totpop,
        cast (m_totpop as float) as m_totpop,
        cast (e_hu as float) as e_hu,
        cast (m_hu as float) as m_hu,
        cast (e_hh as float) as e_hh,
        cast (m_hh as float) as m_hh,
        cast (e_pov150 as float) as e_pov150,
        cast (m_pov150 as float) as m_pov150,
        cast (e_unemp as float) as e_unemp,
        cast (m_unemp as float) as m_unemp,
        cast (e_hburd as float) as e_hburd,
        cast (m_hburd as float) as m_hburd,
        cast (e_nohsdp as float) as e_nohsdp,
        cast (m_nohsdp as float) as m_nohsdp,
        cast (e_uninsur as float) as e_uninsur,
        cast (m_uninsur as float) as m_uninsur,
        cast (e_age65 as float) as e_age65,
        cast (m_age65 as float) as m_age65,
        cast (e_age17 as float) as e_age17,
        cast (m_age17 as float) as m_age17,
        cast (e_disabl as float) as e_disabl,
        cast (m_disabl as float) as m_disabl,
        cast (e_sngpnt as float) as e_sngpnt,
        cast (m_sngpnt as float) as m_sngpnt,
        cast (e_limeng as float) as e_limeng,
        cast (m_limeng as float) as m_limeng,
        cast (e_minrty as float) as e_minrty,
        cast (m_minrty as float) as m_minrty,
        cast (e_munit as float) as e_munit,
        cast (m_munit as float) as m_munit,
        cast (e_mobile as float) as e_mobile,
        cast (m_mobile as float) as m_mobile,
        cast (e_crowd as float) as e_crowd,
        cast (m_crowd as float) as m_crowd,
        cast (e_noveh as float) as e_noveh,
        cast (m_noveh as float) as m_noveh,
        cast (e_groupq as float) as e_groupq,
        cast (m_groupq as float) as m_groupq,
        cast (ep_pov150 as float) as ep_pov150,
        cast (mp_pov150 as float) as mp_pov150,
        cast (ep_unemp as float) as ep_unemp,
        cast (mp_unemp as float) as mp_unemp,
        cast (ep_hburd as float) as ep_hburd,
        cast (mp_hburd as float) as mp_hburd,
        cast (ep_nohsdp as float) as ep_nohsdp,
        cast (mp_nohsdp as float) as mp_nohsdp,
        cast (ep_uninsur as float) as ep_uninsur,
        cast (mp_uninsur as float) as mp_uninsur,
        cast (ep_age65 as float) as ep_age65,
        cast (mp_age65 as float) as mp_age65,
        cast (ep_age17 as float) as ep_age17,
        cast (mp_age17 as float) as mp_age17,
        cast (ep_disabl as float) as ep_disabl,
        cast (mp_disabl as float) as mp_disabl,
        cast (ep_sngpnt as float) as ep_sngpnt,
        cast (mp_sngpnt as float) as mp_sngpnt,
        cast (ep_limeng as float) as ep_limeng,
        cast (mp_limeng as float) as mp_limeng,
        cast (ep_minrty as float) as ep_minrty,
        cast (mp_minrty as float) as mp_minrty,
        cast (ep_munit as float) as ep_munit,
        cast (mp_munit as float) as mp_munit,
        cast (ep_mobile as float) as ep_mobile,
        cast (mp_mobile as float) as mp_mobile,
        cast (ep_crowd as float) as ep_crowd,
        cast (mp_crowd as float) as mp_crowd,
        cast (ep_noveh as float) as ep_noveh,
        cast (mp_noveh as float) as mp_noveh,
        cast (ep_groupq as float) as ep_groupq,
        cast (mp_groupq as float) as mp_groupq,
        cast (epl_pov150 as float) as epl_pov150,
        cast (epl_unemp as float) as epl_unemp,
        cast (epl_hburd as float) as epl_hburd,
        cast (epl_nohsdp as float) as epl_nohsdp,
        cast (epl_uninsur as float) as epl_uninsur,
        cast (spl_theme1 as float) as spl_theme1,
        cast (rpl_theme1 as float) as rpl_theme1,
        cast (epl_age65 as float) as epl_age65,
        cast (epl_age17 as float) as epl_age17,
        cast (epl_disabl as float) as epl_disabl,
        cast (epl_sngpnt as float) as epl_sngpnt,
        cast (epl_limeng as float) as epl_limeng,
        cast (spl_theme2 as float) as spl_theme2,
        cast (rpl_theme2 as float) as rpl_theme2,
        cast (epl_minrty as float) as epl_minrty,
        cast (spl_theme3 as float) as spl_theme3,
        cast (rpl_theme3 as float) as rpl_theme3,
        cast (epl_munit as float) as epl_munit,
        cast (epl_mobile as float) as epl_mobile,
        cast (epl_crowd as float) as epl_crowd,
        cast (epl_noveh as float) as epl_noveh,
        cast (epl_groupq as float) as epl_groupq,
        cast (spl_theme4 as float) as spl_theme4,
        cast (rpl_theme4 as float) as rpl_theme4,
        cast (spl_themes as float) as spl_themes,
        cast (rpl_themes as float) as rpl_themes,
        cast (f_pov150 as float) as f_pov150,
        cast (f_unemp as float) as f_unemp,
        cast (f_hburd as float) as f_hburd,
        cast (f_nohsdp as float) as f_nohsdp,
        cast (f_uninsur as float) as f_uninsur,
        cast (f_theme1 as float) as f_theme1,
        cast (f_age65 as float) as f_age65,
        cast (f_age17 as float) as f_age17,
        cast (f_disabl as float) as f_disabl,
        cast (f_sngpnt as float) as f_sngpnt,
        cast (f_limeng as float) as f_limeng,
        cast (f_theme2 as float) as f_theme2,
        cast (f_minrty as float) as f_minrty,
        cast (f_theme3 as float) as f_theme3,
        cast (f_munit as float) as f_munit,
        cast (f_mobile as float) as f_mobile,
        cast (f_crowd as float) as f_crowd,
        cast (f_noveh as float) as f_noveh,
        cast (f_groupq as float) as f_groupq,
        cast (f_theme4 as float) as f_theme4,
        cast (f_total as float) as f_total,
        cast (e_daypop as float) as e_daypop,
        cast (e_noint as float) as e_noint,
        cast (m_noint as float) as m_noint,
        cast (e_afam as float) as e_afam,
        cast (m_afam as float) as m_afam,
        cast (e_hisp as float) as e_hisp,
        cast (m_hisp as float) as m_hisp,
        cast (e_asian as float) as e_asian,
        cast (m_asian as float) as m_asian,
        cast (e_aian as float) as e_aian,
        cast (m_aian as float) as m_aian,
        cast (e_nhpi as float) as e_nhpi,
        cast (m_nhpi as float) as m_nhpi,
        cast (e_twomore as float) as e_twomore,
        cast (m_twomore as float) as m_twomore,
        cast (e_otherrace as float) as e_otherrace,
        cast (m_otherrace as float) as m_otherrace,
        cast (ep_noint as float) as ep_noint,
        cast (mp_noint as float) as mp_noint,
        cast (ep_afam as float) as ep_afam,
        cast (mp_afam as float) as mp_afam,
        cast (ep_hisp as float) as ep_hisp,
        cast (mp_hisp as float) as mp_hisp,
        cast (ep_asian as float) as ep_asian,
        cast (mp_asian as float) as mp_asian,
        cast (ep_aian as float) as ep_aian,
        cast (mp_aian as float) as mp_aian,
        cast (ep_nhpi as float) as ep_nhpi,
        cast (mp_nhpi as float) as mp_nhpi,
        cast (ep_twomore as float) as ep_twomore,
        cast (mp_twomore as float) as mp_twomore,
        cast (ep_otherrace as float) as ep_otherrace,
        cast (mp_otherrace as float) as mp_otherrace

    from source

)

select * from renamed
where rpl_themes >= 0