CREATE TABLE [BIRTH_RELATIONSHIP] (
  [BIRTHID] nvarchar(255) PRIMARY KEY NOT NULL,
  [PREGNANCYID] nvarchar(255),
  [PATID] nvarchar(255) NOT NULL,
  [ENCOUNTERID] nvarchar(255),
  [MOTHERID] nvarchar(255),
  [MOTHER_ENCOUNTERID] nvarchar(255)
)
GO

ALTER TABLE [BIRTH_RELATIONSHIP] ADD FOREIGN KEY ([PATID]) REFERENCES [DEMOGRAPHICS] ([PATID])
GO

ALTER TABLE [BIRTH_RELATIONSHIP] ADD FOREIGN KEY ([ENCOUNTERID]) REFERENCES [ENCOUNTER] ([ENCOUNTERID])
GO

ALTER TABLE [BIRTH_RELATIONSHIP] ADD FOREIGN KEY ([MOTHERID]) REFERENCES [DEMOGRAPHICS] ([PATID])
GO

ALTER TABLE [BIRTH_RELATIONSHIP] ADD FOREIGN KEY ([MOTHER_ENCOUNTERID]) REFERENCES [ENCOUNTER] ([ENCOUNTERID])
GO