select
    vitalid,
    patid,
    encounterid,
    cast(measure_date as date) measure_date,
    cast(measure_time as time) measure_time,
    vital_source,
    ht,
    wt,
    diastolic,
    systolic,
    original_bmi,
    bp_position,
    smoking,
    tobacco,
    tobacco_type,
    raw_vital_source,
    raw_ht,
    raw_wt,
    raw_diastolic,
    raw_systolic,
    raw_bp_position,
    raw_smoking,
    raw_tobacco,
    raw_tobacco_type
from
    {{ ref('stg_pcornet__vital') }}